In [47]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [48]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
new_data = [
    ['John', 'Anna', 'Peter', 'Linda'],
    [28, 34, 29, 42],
    ['New York', 'Paris', 'Berlin', 'London'],
    [65000, 70000, 62000, 85000]
]
df1 = pd.DataFrame(new_data)
df1

          0      1       2       3
0      John   Anna   Peter   Linda
1        28     34      29      42
2  New York  Paris  Berlin  London
3     65000  70000   62000   85000

In [50]:
Fresh_data = [
    ['John', 'Anna', 'Peter', 'Linda'],
    [28, 34, 29, 42],
    ['New York', 'Paris', 'Berlin', 'London'],
    [65000, 70000, 62000, 85000]
]
df2 = pd.DataFrame(Fresh_data)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(Fresh_data, columns=columns)
df2

       Name    Age    City  Salary
0      John   Anna   Peter   Linda
1        28     34      29      42
2  New York  Paris  Berlin  London
3     65000  70000   62000   85000

Selection and Indexing of columns

In [51]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [52]:
df[['Age','City']]

   Age      City
0   28  New York
1   34     Paris
2   29    Berlin
3   42    London

Creating a new column

In [53]:
df['Designation'] = ['Engineer', 'Manager', 'Analyst', 'Director']
Fresh_data

[['John', 'Anna', 'Peter', 'Linda'],
 [28, 34, 29, 42],
 ['New York', 'Paris', 'Berlin', 'London'],
 [65000, 70000, 62000, 85000]]

Remove a column from the DataFrame using the drop() method. For example, to remove the 'Salary' column:

In [54]:
df.drop('Designation', axis=1, inplace=True)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [55]:
df.drop(['City','Salary'], axis=1, inplace=True)
df

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [56]:
df.drop(0, axis=0, inplace=True)
df

    Name  Age
1   Anna   34
2  Peter   29
3  Linda   42

Selecting rows based on conditions:

In [57]:
Raw_data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(Raw_data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [59]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [61]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [62]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [63]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [67]:
df.loc[0:2][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000
2    Berlin   62000

Conditional selection in pandas allows you to filter data based on specific conditions. You can use boolean indexing to select rows that meet certain criteria. Here's an example:

In [68]:
df[df['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [70]:
df[(df['Age']>30) & (df['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000